// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './ems-allure.otf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

const bundle = {
  version: 1,
  family: 'EMS Allure Tegaki 14aaaz',
  lineCap: 'round',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'EMS Allure Tegaki 14aaaz'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1102,
  descender: -446,
  glyphData,
} as const;

export default bundle;
