// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './lxgw-wenkai-fbeec9e6.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'LXGW WenKai Tegaki fbeec9e6',
  lineCap: 'round',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'LXGW WenKai Tegaki fbeec9e6'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 928,
  descender: -256,
  glyphData,
  glyphDataById,
  features: ["afrc","calt","ccmp","dlig","frac","salt","subs","sups","vert"],
} as const;

export default bundle;
