// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './atma-9016c5b9.ttf' with { type: 'url' };
import fullFontUrl from './atma.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Atma Tegaki 9016c5b9',
  fullFamily: 'Atma',
  lineCap: 'round',
  fontUrl,
  fullFontUrl,
  fontFaceCSS: `@font-face { font-family: 'Atma Tegaki 9016c5b9'; src: url(${fontUrl}); } @font-face { font-family: 'Atma'; src: url(${fullFontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1101,
  descender: -518,
  glyphData,
  glyphDataById,
  features: ["akhn","blwf","half","init","nukt","pres","pstf","psts","rphf"],
} as const;

export default bundle;
