// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './atma-5e72fa2e.ttf' with { type: 'url' };
import fullFontUrl from './atma.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 1,
  family: 'Atma Tegaki 5e72fa2e',
  fullFamily: 'Atma',
  lineCap: 'round',
  fontUrl,
  fullFontUrl,
  fontFaceCSS: `@font-face { font-family: 'Atma Tegaki 5e72fa2e'; src: url(${fontUrl}); } @font-face { font-family: 'Atma'; src: url(${fullFontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1101,
  descender: -518,
  glyphData,
  glyphDataById,
  features: ["akhn","blwf","half","init","nukt","pres","pstf","psts","rphf"],
} as const;

export default bundle;
