// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './nanum-pen-script-38efadb5.ttf' with { type: 'url' };
import fullFontUrl from './nanum-pen-script.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Nanum Pen Script Tegaki 38efadb5',
  fullFamily: 'Nanum Pen Script',
  lineCap: 'round',
  fontUrl,
  fullFontUrl,
  fontFaceCSS: `@font-face { font-family: 'Nanum Pen Script Tegaki 38efadb5'; src: url(${fontUrl}); } @font-face { font-family: 'Nanum Pen Script'; src: url(${fullFontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 800,
  descender: -200,
  glyphData,
} as const;

export default bundle;
