#!/usr/bin/env bun
/**
 * build-letterpaths-data.ts — writes `src/stroke-order/letterpaths-data.ts`:
 * the letter-formation models of https://github.com/RobinL/letterpaths (MIT),
 * fetched from a pinned commit and flattened to polylines.
 *
 * Letterpaths draws each letter the way handwriting is taught: cubic Béziers
 * in pen order and direction, each stroke `main` (written with the letter)
 * or `deferred` (after it — an i's dot, a t's cross), dots as `mark` strokes.
 * Three sets: print letters (A–Z, a–z), and cursive lowercase in two entry
 * variants — `low` (joined from the baseline) and `high` (from the top of an
 * o, v or w). The cursive letters keep their entry and lead-out: a script
 * font's letter carries the same joins. One fix-up: bars run left to right
 * (print f's crossbar is the one that doesn't).
 *
 * Run: bun scripts/build-letterpaths-data.ts
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const COMMIT = '88c9e083f0acf8c3868576cf167769d05c7a65f9';
const BASE = `https://raw.githubusercontent.com/RobinL/letterpaths/${COMMIT}`;
const DATA = `${BASE}/packages/letterpaths/src/data/bezier`;

interface Pt {
  x: number;
  y: number;
}
interface Cubic {
  p0: Pt;
  p1: Pt;
  p2: Pt;
  p3: Pt;
}
interface Letter {
  strokes: { kind: 'stroke' | 'mark'; phase: 'main' | 'deferred'; curves: Cubic[] }[];
}

/** Samples per cubic; the pipeline resamples by arc length, so this only needs to hold the curve's shape. */
const SAMPLES = 8;

function flatten(curves: Cubic[]): [number, number][] {
  const out: [number, number][] = [];
  const at = (c: Cubic, t: number): [number, number] => {
    const u = 1 - t;
    const a = u * u * u;
    const b = 3 * u * u * t;
    const d = 3 * u * t * t;
    const e = t * t * t;
    return [a * c.p0.x + b * c.p1.x + d * c.p2.x + e * c.p3.x, a * c.p0.y + b * c.p1.y + d * c.p2.y + e * c.p3.y];
  };
  curves.forEach((c, i) => {
    for (let k = i === 0 ? 0 : 1; k <= SAMPLES; k++) {
      const [x, y] = at(c, k / SAMPLES);
      const p: [number, number] = [Math.round(x), Math.round(y)];
      const last = out.at(-1);
      if (!last || last[0] !== p[0] || last[1] !== p[1]) out.push(p);
    }
  });
  return out;
}

/**
 * A bar — a stroke that runs across, rising less than a tenth of its width —
 * written left to right. Every bar in the set is, but print f's crossbar.
 */
function barLeftToRight(points: [number, number][]): [number, number][] {
  const a = points[0]!;
  const b = points.at(-1)!;
  const ys = points.map((p) => p[1]);
  const bar = points.length > 1 && Math.max(...ys) - Math.min(...ys) < 0.1 * Math.abs(b[0] - a[0]);
  return bar && b[0] < a[0] ? [...points].reverse() : points;
}

/** A letter's strokes in writing order: the main ones, then the deferred. */
function strokesOf(letter: Letter): [number, number][][] {
  const main = letter.strokes.filter((s) => s.phase !== 'deferred');
  const deferred = letter.strokes.filter((s) => s.phase === 'deferred');
  return [...main, ...deferred].map((s) => barLeftToRight(flatten(s.curves)));
}

async function fetchLetter(path: string): Promise<Letter> {
  const response = await fetch(`${DATA}/${path}`);
  if (!response.ok) throw new Error(`${path}: ${response.status}`);
  return (await response.json()) as Letter;
}

const LOWER = 'abcdefghijklmnopqrstuvwxyz';
const sets: Record<string, Record<string, [number, number][][]>> = { PRINT: {}, CURSIVE_LOW: {}, CURSIVE_HIGH: {} };
for (const c of LOWER.toUpperCase()) sets.PRINT![c] = strokesOf(await fetchLetter(`print/${c}-upper-print-bezier.json`));
for (const c of LOWER) {
  sets.PRINT![c] = strokesOf(await fetchLetter(`print/${c}-lower-print-bezier.json`));
  sets.CURSIVE_LOW![c] = strokesOf(await fetchLetter(`entry-low/${c}-lower-cursive-bezier-entry-low.json`));
  sets.CURSIVE_HIGH![c] = strokesOf(await fetchLetter(`entry-high/${c}-lower-cursive-bezier-entry-high.json`));
}
const license = (await (await fetch(`${BASE}/LICENSE`)).text()).trim();

let out = `// GENERATED by scripts/build-letterpaths-data.ts — do not edit by hand.
//
// Letter-formation models from https://github.com/RobinL/letterpaths at
// ${COMMIT.slice(0, 7)}, flattened to polylines: [x, y] pairs in a y-down frame
// of about 1000 units, each stroke in pen order. Consultation-only here: the
// polylines inform stroke order and direction and never enter generated
// bundles.
//
${license
  .split('\n')
  .map((line) => `// ${line}`.trimEnd())
  .join('\n')}

// Each glyph is its strokes joined by '|', each a run of 'x,y' points joined
// by spaces (decoded by letterpaths.ts).
`;
const DOCS: Record<string, string> = {
  PRINT: 'Print letters, A–Z and a–z.',
  CURSIVE_LOW: 'Cursive lowercase, entering from the baseline.',
  CURSIVE_HIGH: 'Cursive lowercase, entering from the top of an o, v or w.',
};
for (const [name, glyphs] of Object.entries(sets)) {
  const encoded = Object.fromEntries(
    Object.entries(glyphs).map(([c, strokes]) => [c, strokes.map((s) => s.map((p) => p.join(',')).join(' ')).join('|')]),
  );
  out += `\n/** ${DOCS[name]} */\nexport const LETTERPATHS_${name}: Record<string, string> = {\n${Object.entries(encoded)
    .map(([c, s]) => `  ${JSON.stringify(c)}: ${JSON.stringify(s)},`)
    .join('\n')}\n};\n`;
}
const target = join(import.meta.dir, '../src/stroke-order/letterpaths-data.ts');
writeFileSync(target, out);
console.log(`Wrote ${target}`);
