#!/usr/bin/env bun
/**
 * build-hershey-data.ts — writes `src/stroke-order/hershey-jhf.ts`: the raw
 * JHF text of the Hershey faces the generator consults, fetched from a pinned
 * commit of https://github.com/kamalmostafa/hershey-fonts and parsed at load
 * time by `stroke-order/jhf.ts`.
 *
 * Only the SIMPLEX faces are pen paths: the duplex, complex and triplex
 * faces (futuram, scriptc, timesi, the Cyrillic ones, …) draw thick parts
 * as several parallel lines. Of the simplex faces, `cursive` repeats
 * `scripts` and `rowmans` repeats `futural` nearly line for line.
 *
 * Run: bun scripts/build-hershey-data.ts
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const COMMIT = '1356bf2f83d380fcef68c887e88675eb9d445d86';
const FACES = {
  scripts: 'Script simplex — formal cursive',
  futural: 'Simplex Roman — plain print Latin and digits',
  greeks: 'Greek simplex — the Greek alphabet in plain print',
} as const;

const url = (face: string) => `https://raw.githubusercontent.com/kamalmostafa/hershey-fonts/${COMMIT}/hershey-fonts/${face}.jhf`;

let out = `// GENERATED by scripts/build-hershey-data.ts — do not edit by hand.
//
// Raw JHF text of the Hershey simplex faces, from
// https://github.com/kamalmostafa/hershey-fonts at ${COMMIT.slice(0, 7)}; parsed by
// jhf.ts. The Hershey Fonts were originally created by Dr. A. V. Hershey while
// working at the U. S. National Bureau of Standards. The format of the font
// data was originally created by James Hurt, Cognition, Inc., 900 Technology
// Park Drive, Billerica, MA 01821. Consultation-only here: the polylines
// inform stroke order and direction and never enter generated bundles.
`;
for (const [face, description] of Object.entries(FACES)) {
  const response = await fetch(url(face));
  if (!response.ok) throw new Error(`${face}.jhf: ${response.status}`);
  const text = (await response.text()).replace(/\r\n/g, '\n');
  out += `\n/** ${face}.jhf: ${description}. */\nexport const ${face.toUpperCase()}_JHF = ${JSON.stringify(text)};\n`;
}
const target = join(import.meta.dir, '../src/stroke-order/hershey-jhf.ts');
writeFileSync(target, out);
console.log(`Wrote ${target}`);
