// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './hershey-script-1-stroke.otf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

const bundle = {
  version: 1,
  family: 'Hershey Script 1-stroke Tegaki vp8jn0',
  lineCap: 'round',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Hershey Script 1-stroke Tegaki vp8jn0'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1079,
  descender: -408,
  glyphData,
} as const;

export default bundle;
