// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './ma-shan-zheng.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Ma Shan Zheng',
  lineCap: 'round',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Ma Shan Zheng'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 880,
  descender: -120,
  glyphData,
} as const;

export default bundle;
